# Generated by Django 2.1.4 on 2019-02-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique_for_date='created')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
