# Generated by Django 2.1.4 on 2019-02-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('amount_to_spend', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_expense', to='tourism.Destinations')),
            ],
        ),
    ]
