# Generated by Django 2.1.4 on 2019-04-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_expenses_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='label',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='destinations',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
