# Generated by Django 2.1.4 on 2019-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_auto_20190404_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='src',
            field=models.URLField(blank=True),
        ),
    ]
